### ISSUE TITLE
Typo in code in Q4 of 4 in Update Existing Page Content lesson

### ISSUE THREAD

**Issue by sarah-maris** [udacity/course-issues-ud711#10]
Link to lesson: https://classroom.udacity.com/courses/ud117/lessons/39d760cf-9593-420d-9a97-57bff31e29c1/concepts/c7c27fc1-e611-4b5c-84e3-7d1b0075b45f

The HTML element  is shown as:
```
<h1 id=""test"">Ice Cream Flavors</h1>
```

Should not have two sets of quotes around id name.  Should be:
```
<h1 id="test">Ice Cream Flavors</h1>
```

**Comment by hbkwong** [comment]
@sarah-maris Fixed! Thanks for reporting this one.
