### ISSUE TITLE
Missing in option in Style Page Content Q 1 of 6

### ISSUE THREAD

**Issue by sarah-maris** [udacity/course-issues-ud711#11]
Link to lesson: https://classroom.udacity.com/courses/ud117/lessons/39d760cf-9593-420d-9a97-57bff31e29c1/concepts/3734dc32-5300-4ad9-96a8-be488f96a180

The text for one of the options seems incomplete:

![image](https://user-images.githubusercontent.com/6298143/34027254-93884ac8-e129-11e7-9ad6-5d9b4b9efc42.png)

Looking at the HTML:
```
<p>rules in a <style> tag</p>
</style></p>
```
 I'm guessing that this should be "rules in style tag"

**Comment by hbkwong** [comment]
The markdown doesn't show up, so I wrapped it in backticks. We should be good to go now!  Thanks for reporting this,  @sarah-maris.
