### ISSUE TITLE
Not accessible in India

### ISSUE THREAD

**Issue by nimitbhargava** [udacity/course-issues-ud711#12]
https://www.udacity.com/course/object-oriented-javascript--ud711 redirects to https://in.udacity.com/course/object-oriented-javascript--ud711 and then again redirects to https://in.udacity.com/404

**Comment by richardkalehoff** [comment]
This issue has been submitted to an internal team for correction. I'll update this ticket when it's been resolved. Thanks for letting us know!

**Comment by hbkwong** [comment]
Fixed! @nimitbhargava
