### ISSUE TITLE
Markdown Missing Backtick

### ISSUE THREAD

**Issue by walesmd** [udacity/course-issues-ud711#2]
A code sample used in a quiz is missing an opening backtick, causing the code to not be formatted properly.

URL: https://classroom.udacity.com/courses/ud711/lessons/504843ae-ba16-4573-a859-94da7a7d1dd4/concepts/2bbcfed5-e683-431b-ace2-b67c091400d2

2nd "house object" quiz

**Comment by veronikabenkeser** [comment]
Thank you, Michael! Just fixed it.
