### ISSUE TITLE
Confusing Question

### ISSUE THREAD

**Issue by walesmd** [udacity/course-issues-ud711#3]
https://classroom.udacity.com/courses/ud711/lessons/504843ae-ba16-4573-a859-94da7a7d1dd4/concepts/2bbcfed5-e683-431b-ace2-b67c091400d2

Question 5 of 6 is confusing. Particularly because changeToApple() is never actually called in the code sample.

It feels like trickery, just because the parameter name and variable being modified within the function have the same name as the variable defined in the outer scope.

If changeToApple lacked the passed parameter, the call to changeToApple() would in-fact alter the value of the variable defined in the outer scope.

**Comment by hbkwong** [comment]
Totally with you on this one. It kinda adds a roadblock that unnecessarily clouds the student's thought process. The entire point is to demonstrate primitives being passed by value anyways. We'll update this one!
