### ISSUE TITLE
Dropped a word

### ISSUE THREAD

**Issue by walesmd** [udacity/course-issues-ud711#4]
https://classroom.udacity.com/courses/ud711/lessons/504843ae-ba16-4573-a859-94da7a7d1dd4/concepts/bd94ce28-164e-4ee5-b2bb-819798f22218

Question 1 of 6, option 4:

"A method is a property **that** points to a function."

**Comment by veronikabenkeser** [comment]
Thank you, Michael! Just fixed it.
