### ISSUE TITLE
Q 2 of 4 not working in Nodes, Elements, and Interfaces...Oh My!

### ISSUE THREAD

**Issue by sarah-maris** [udacity/course-issues-ud711#7]
Link to quiz: https://classroom.udacity.com/courses/ud117/lessons/74c2a096-61db-4302-9d65-6b7fa9b8c329/concepts/360fd77c-3a6d-4256-bdf3-a792363e672a

The quiz will only pass if you check all three options.

![capture](https://user-images.githubusercontent.com/6298143/34011943-e0ceb76c-e0df-11e7-885e-85139f5078eb.PNG)

It will not pass if you choose Element Interface (which is the correct answer) 

![image](https://user-images.githubusercontent.com/6298143/34011940-dbc21278-e0df-11e7-9b0b-f0d9dce5d6d8.png)

**Comment by veronikabenkeser** [comment]
Thank you, Sarah! Fixed.
