### ISSUE TITLE
3rd querySelectorAll quiz in More Ways To Access Elements not accepting correct answer

### ISSUE THREAD

**Issue by sarah-maris** [udacity/course-issues-ud711#8]
Link to lesson:  https://classroom.udacity.com/courses/ud117/lessons/74c2a096-61db-4302-9d65-6b7fa9b8c329/concepts/eee59c35-d033-4714-b331-b042b7a36564

This code does not pass:
```
document.querySelectorAll('.articles p');
```

but unless I am interpreting the question incorrectly, it should.

**Comment by veronikabenkeser** [comment]
Thank you for brining this to our attention, Sarah! Just fixed it.
