### ISSUE TITLE
Bad link for repo in Creating Content with JavaScript

### ISSUE THREAD

**Issue by sarah-maris** [udacity/course-issues-ud711#9]
Here is a link to the lessons with bad links:

Intro: https://classroom.udacity.com/courses/ud117/lessons/39d760cf-9593-420d-9a97-57bff31e29c1/concepts/24b00792-38d0-4d61-acc9-eb1422fcc284

Update Existing Page Content:  https://classroom.udacity.com/courses/ud117/lessons/39d760cf-9593-420d-9a97-57bff31e29c1/concepts/c7c27fc1-e611-4b5c-84e3-7d1b0075b45f

In the lesson Richard asks us to download the project repo for the course - but the link doesn't work:

![image](https://user-images.githubusercontent.com/6298143/34026641-6d4ecb24-e125-11e7-9d3c-3f63f606416b.png)

**Comment by richardkalehoff** [comment]
Oops! Forgot to make this public. Thanks, Sarah!
